@startuml Diagrama de Entidad Relacion
entity Producto {
    idProducto: int <<PK>>
    descripcion: String
    stock: int
    stockMinimo: int
    idMarca: int <<FK>>
    idCategoria: int <<FK>>
    idProveedor: int <<FK>>
}

entity Marca {
    idMarca: int <<PK>>
    nombre: String
}

entity Categoria {
    idCategoria: int <<PK>>
    nombre: String
}

entity Proveedor {
    idProveedor: int <<PK>>
    nombre: String
    direccion: String
    telefono: String
    email: String
    idCiudad: int <<FK>>
}

entity City {
    idCiudad: int <<PK>>
    name: String
    latitude: decimal
    longitud: decimal
    Province: int <<FK>>
}

entity Province {
    idProvince: int <<PK>>
    name: String
    latitude: decimal
    longitud: decimal
    country: int <<FK>>
}

entity Pais {
    idPais: int <<PK>>
    name: String
    code: int
}

entity Pedido {
    idPedido: int <<PK>>
    fecha: date
    idProveedor: int <<FK>>
}

entity DetallePedido {
    idDetallePedido: int <<PK>>
    cantidad: int
    idPedido: int <<FK>>
    idProducto: int <<FK>>
}

entity Entrada {
    idEntrada: int <<PK>>
    fecha: date
}

entity DetalleEntrada {
    idDetalleEntrada: int <<PK>>
    cantidad: int
    idEntrada: int <<FK>>
    idProducto: int <<FK>>
}

entity Salida {
    idSalida: int <<PK>>
    fecha: date
}

entity DetalleSalida {
    idDetalleSalida: int <<PK>>
    cantidad: int
    idSalida: int <<FK>>
    idProducto: int <<FK>>
}

entity Usuario {
    idUSer: int <<PK>>
    firstName: string
    lastName: string
    email: string
    password: string
    birthDate: date
    role: string
    idCity: int <<FK>>
}

Producto }|--|| Marca
Producto }|--|| Categoria
Producto }|--|| Proveedor
Proveedor }|--|| City
Usuario }|--|| City 
City }|--|| Province
Province }|--|| Pais
Pedido }|--|| Proveedor
DetallePedido }|--|| Pedido
DetallePedido }|--|| Producto
DetalleEntrada }|--|| Entrada
DetalleEntrada }|--|| Producto
DetalleSalida }|--|| Salida
DetalleSalida }|--|| Producto

@enduml