@startuml Diagrama de Entidad Relacion
left to right direction
entity Producto {
    codigoDeBarras: int <<PK>>
    descripcion: String
    stock: int
    stockMinimo: int
    idMarca: int <<FK>>
    idCategoria: int <<FK>>
    idProveedor: int <<FK>>
}

entity Marca {
    idMarca: int <<PK>>
    nombre: String
}

entity Categoria {
    idCategoria: int <<PK>>
    nombre: String
}

entity Proveedor {
    idProveedor: int <<PK>>
    nombre: String
    direccion: String
    telefono: String
    email: String
    ciudad: int <<FK>>
}

entity Ciudad {
    idCiudad: int <<PK>>
    nombre: String
    latitud: decimal
    longitud: decimal
    provincia: int <<FK>>
}

entity Provincia {
    idProvince: int <<PK>>
    nombre: String
    latitud: decimal
    longitud: decimal
    pais: int <<FK>>
}

entity Pais {
    idPais: int <<PK>>
    nombre: String
}

entity Pedido {
    idPedido: int <<PK>>
    fecha: date
    proveedor: int <<FK>>
}

entity DetallePedido {
    idDetallePedido: int <<PK>>
    cantidad: int
    pedido: int <<FK>>
    producto: int <<FK>>
}

entity Entrada {
    idEntrada: int <<PK>>
    fecha: date
}

entity DetalleEntrada {
    idDetalleEntrada: int <<PK>>
    cantidad: int
    entrada: int <<FK>>
    producto: int <<FK>>
}

entity Salida {
    idSalida: int <<PK>>
    fecha: date
}

entity DetalleSalida {
    idDetalleSalida: int <<PK>>
    cantidad: int
    idSalida: int <<FK>>
    idProducto: int <<FK>>
}

entity Usuario {
    idUsuario: int <<PK>>
    nombre: string
    apellido: string
    email: string
    contraseña: string
    ciudad: int <<FK>>
}

Producto }|--|| Marca
Producto }|--|| Categoria
Producto }|--|| Proveedor
Proveedor }|--|| Ciudad
Usuario }|--|| Ciudad
Ciudad }|--|| Provincia
Provincia }|--|| Pais
Pedido }|--|| Proveedor
DetallePedido }|--|| Pedido
DetallePedido }|--|| Producto
DetalleEntrada }|--|| Entrada
DetalleEntrada }|--|| Producto
DetalleSalida }|--|| Salida
DetalleSalida }|--|| Producto

@enduml